# Generated by Django 4.0.6 on 2022-07-27 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=106)),
                ('email', models.EmailField(max_length=106)),
                ('mobile', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=106)),
                ('lastname', models.CharField(max_length=106)),
                ('user_profile_picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
