# Generated by Django 4.0.6 on 2022-07-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_profile_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
